// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2bbdd557-443a-4c50-9dc0-911cc335b6e4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EQPFfEPIA",
    "aws_user_pools_web_client_id": "2fm8p89m9ip9ef0gtvltrvihok",
    "aws_appsync_graphqlEndpoint": "https://mdyvx4gp2zh27ercqnfqwlheve.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "amplifynotetaker-20191122055504-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifynotetaker-20191122055504-hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
